/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PolicymakerRouteImport } from './routes/policymaker'
import { Route as IndexRouteImport } from './routes/index'

const PolicymakerRoute = PolicymakerRouteImport.update({
  id: '/policymaker',
  path: '/policymaker',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/policymaker': typeof PolicymakerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/policymaker': typeof PolicymakerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/policymaker': typeof PolicymakerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/policymaker'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/policymaker'
  id: '__root__' | '/' | '/policymaker'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PolicymakerRoute: typeof PolicymakerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/policymaker': {
      id: '/policymaker'
      path: '/policymaker'
      fullPath: '/policymaker'
      preLoaderRoute: typeof PolicymakerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PolicymakerRoute: PolicymakerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
